language: objective-c
osx_image: xcode8.0

script:
  set -o pipefail && xcodebuild test -project ReadabilityKit.xcodeproj -scheme 'ReadabilityKit iOS' -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty;
